apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - name: mysqlport
          containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_DATABASE
          value: admin
        - name: MYSQL_ROOT_PASSWORD
          value: admin
