apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: demo-app-spc
  namespace: app
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/gke-arena/secrets/MYSQL_DATABASE/versions/latest"
        path: "MYSQL_DATABASE"
      - resourceName: "projects/gke-arena/secrets/MYSQL_ROOT_PASSWORD/versions/latest"
        path: "MYSQL_ROOT_PASSWORD"
