---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: app
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      serviceAccountName: demo-app-sa  # Must have access to Secret Manager
      containers:
        - name: test-app
          image: python-app:v1-f841132-20250617122146
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: secrets-store
              mountPath: "/var/secrets"
              readOnly: true
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "demo-app-spc"
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace : app
spec:
  type: LoadBalancer
  ports:
  - name: test-service
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: test-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app-sa
  namespace: app
---
apiVersion: v1
kind: Namespace
metadata:
  name: app
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: python-app:v1-f841132-20250617122146
        ports:
        - name: mysqlport
          containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_DATABASE
          value: admin
        - name: MYSQL_ROOT_PASSWORD
          value: admin
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: app
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: http
  selector:
    app: mysql
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: demo-app-spc
  namespace: app
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/gke-arena/secrets/MYSQL_DATABASE/versions/latest"
        path: "MYSQL_DATABASE"
      - resourceName: "projects/gke-arena/secrets/MYSQL_ROOT_PASSWORD/versions/latest"
        path: "MYSQL_ROOT_PASSWORD"
---
