# .github/workflows/promote-to-prod.yaml
name: Promote to Production GAR (Prod)

on:
  workflow_dispatch:
    # Optional inputs for manual promotion, e.g., to override the default image tag
    inputs:
      image_tag:
        description: 'Optional: Specific image tag to promote (e.g., commit SHA or release version)'
        required: false
jobs:
  promote:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for Workload Identity Federation (GCP)
      contents: write # Required to commit changes to the repo
    
    steps:
      - name: Checkout stage branch (to get current stage image)
        uses: actions/checkout@v4
        with:
          ref: stage
          fetch-depth: 0 # Needed to read the manifests/stage/deployment.yaml

      - name: Install yq
        run: |
           sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
           sudo chmod a+x /usr/local/bin/yq

      - name: Extract image details from staging deployment
        id: extract_stage_image
        run: |
          FULL_STAGE_IMAGE=$(yq -r '.spec.template.spec.containers[0].image' manifests/stage/deployment.yaml)
          echo "Full stage image: $FULL_STAGE_IMAGE"
    
          STAGE_REPO=$(echo "$FULL_STAGE_IMAGE" | cut -d':' -f1)
          STAGE_TAG=$(echo "$FULL_STAGE_IMAGE" | cut -d':' -f2)
          
          PROD_REPO=$(echo "$STAGE_REPO" | \
                      sed 's|praveen-345|shared-vpc-service-315|' | \
                      sed 's|python-app/python-app|prod-python-app/prod-app|')
          
          PROD_TAG="${{ inputs.image_tag }}"
          PROD_TAG="${PROD_TAG:-$STAGE_TAG}"
          
          NEW_PROD_IMAGE="${PROD_REPO}:${PROD_TAG}"
      
          # Print debug info
          echo "STAGE_REPO = $STAGE_REPO"
          echo "STAGE_TAG = $STAGE_TAG"
          echo "PROD_REPO = $PROD_REPO"
          echo "PROD_TAG = $PROD_TAG"
          echo "NEW_PROD_IMAGE = $NEW_PROD_IMAGE"
          
          {
          echo "STAGE_REPO=${STAGE_REPO}"
          echo "STAGE_TAG=${STAGE_TAG}"
          echo "PROD_REPO=${PROD_REPO}"
          echo "PROD_TAG=${PROD_TAG}"
          echo "NEW_PROD_IMAGE=${NEW_PROD_IMAGE}"
          } >> $GITHUB_ENV
          
      - name: Authenticate to GCP using Workload Identity Federation
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/701983950006/locations/global/workloadIdentityPools/gh-prod-pool/providers/gh-prod-provider 
          service_account: github-actions-sa@shared-vpc-service-315.iam.gserviceaccount.com
      - name: Configure gcloud
        run: |
          gcloud config set project shared-vpc-service-31
          gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Pull image from staging GAR
        run: docker pull ${{ env.STAGE_REPO }}:${{ env.STAGE_TAG }}

      - name: Tag image for production GAR
        run: docker tag ${{ env.STAGE_REPO }}:${{ env.STAGE_TAG }} ${{ env.NEW_PROD_IMAGE }}

      - name: Push image to production GAR
        run: docker push ${{ env.NEW_PROD_IMAGE }}

      - name: Checkout main branch (for updating prod manifest)
        uses: actions/checkout@v4
        with:
          ref: main
          path: main-branch

      - name: Update prod deployment with new production image
        run: |
          # Use yq for safer updates
          cd main-branch
          yq e '.spec.template.spec.containers[0].image = "${{ env.NEW_PROD_IMAGE }}"' -i manifests/prod/deployment.yaml

      - name: Commit and push to main
        run: |
          cd main-branch
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add manifests/prod/deployment.yaml
          git commit -m "Promote image to prod: ${{ env.NEW_PROD_IMAGE }} [ci skip]" || echo "No changes to commit"
          git push origin main


